export const Map = {
  Cells: [
    {
      Point: { X: 0, Y: -4, Z: 4 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 1, Y: -4, Z: 3 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 2, Y: -4, Z: 2 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 3, Y: -4, Z: 1 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 4, Y: -4, Z: 0 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -1, Y: -3, Z: 4 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 0, Y: -3, Z: 3 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 1, Y: -3, Z: 2 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 2, Y: -3, Z: 1 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 3, Y: -3, Z: 0 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 4, Y: -3, Z: -1 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -2, Y: -2, Z: 4 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -1, Y: -2, Z: 3 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 0, Y: -2, Z: 2 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 1, Y: -2, Z: 1 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 2, Y: -2, Z: 0 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 3, Y: -2, Z: -1 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 4, Y: -2, Z: -2 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -3, Y: -1, Z: 4 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -2, Y: -1, Z: 3 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -1, Y: -1, Z: 2 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 0, Y: -1, Z: 1 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 1, Y: -1, Z: 0 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 2, Y: -1, Z: -1 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 3, Y: -1, Z: -2 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 4, Y: -1, Z: -3 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -4, Y: 0, Z: 4 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -3, Y: 0, Z: 3 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -2, Y: 0, Z: 2 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -1, Y: 0, Z: 1 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 0, Y: 0, Z: 0 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 1, Y: 0, Z: -1 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 2, Y: 0, Z: -2 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 3, Y: 0, Z: -3 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 4, Y: 0, Z: -4 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -4, Y: 1, Z: 3 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -3, Y: 1, Z: 2 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -2, Y: 1, Z: 1 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -1, Y: 1, Z: 0 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 0, Y: 1, Z: -1 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 1, Y: 1, Z: -2 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 2, Y: 1, Z: -3 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 3, Y: 1, Z: -4 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -4, Y: 2, Z: 2 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -3, Y: 2, Z: 1 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -2, Y: 2, Z: 0 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -1, Y: 2, Z: -1 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 0, Y: 2, Z: -2 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 1, Y: 2, Z: -3 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 2, Y: 2, Z: -4 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -4, Y: 3, Z: 1 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -3, Y: 3, Z: 0 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -2, Y: 3, Z: -1 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -1, Y: 3, Z: -2 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 0, Y: 3, Z: -3 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 1, Y: 3, Z: -4 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -4, Y: 4, Z: 0 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -3, Y: 4, Z: -1 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -2, Y: 4, Z: -2 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: -1, Y: 4, Z: -3 },
      CellType: 1,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
    {
      Point: { X: 0, Y: 4, Z: -4 },
      CellType: 0,
      BuffType: 0,
      OwnerId: null,
      ExpandedData: null,
    },
  ],
};
